-- Run this in Supabase SQL Editor

create table if not exists public.feedback_entries (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null check (type in ('review', 'complaint', 'suggestion')),
  rating smallint check (rating between 1 and 5),
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.feedback_entries enable row level security;

-- Public can read feedback
drop policy if exists "Public can read feedback" on public.feedback_entries;
create policy "Public can read feedback"
on public.feedback_entries
for select
using (true);

-- Public can insert feedback
drop policy if exists "Public can insert feedback" on public.feedback_entries;
create policy "Public can insert feedback"
on public.feedback_entries
for insert
with check (true);
